### ISSUE TITLE
Typescript Support

### ISSUE THREAD

**Issue by antfu** [sibbngheid/variantwind#1]
It would be great if this lib can support Typescript. I would also recommend using [tsup](https://github.com/egoist/tsup) for bundling, it's fast and out-of-box.

**Comment by sibbngheid** [comment]
Learning Typescript is my 2020 goal 😅 Actually I can read it but working with it is another story. 😊

![image](https://user-images.githubusercontent.com/19991745/89738265-ea9bc400-da7f-11ea-8e2c-3f4c0fec8e23.png)

**Comment by antfu** [comment]
Haha, good luck and have fun. If you need, I can make a quick PR as well :)

**Comment by sibbngheid** [comment]
PRs welcome 🤗
