### ISSUE TITLE
Transform template string

### ISSUE THREAD

**Issue by xhebox** [sibbngheid/variantwind#10]
One of my use case is to use it like:

```
variantwind(`
foo
bar
`)
```

But due to https://github.com/sibbngheid/variantwind/blob/master/index.ts#L8, it results into `class: "foobar"` instead of `foo bar`.

I suggest to replace CRLF with a whitespace, instead of an empty string. Then trim spaces around `{}` to prevent split a block ` foo bar ` to `["", "foo", "bar", ""]`.

**Comment by sibbngheid** [comment]
Fixed in v0.12.1. Thanks for reporting.
