### ISSUE TITLE
Error on v0.8.1

### ISSUE THREAD

**Issue by antfu** [sibbngheid/variantwind#5]
![image](https://user-images.githubusercontent.com/11247099/89882951-2064b800-dbfa-11ea-8faa-24ca97563f8b.png)

With Vite, since v0.7.0. Go back to v0.6.0 and everything works fine.

**Comment by sibbngheid** [comment]
Can you share your code where you define `flex-none` class?

**Comment by sibbngheid** [comment]
Can you try v0.8.2?

**Comment by sibbngheid** [comment]
Ok, I found it on icones repo. Newlines was broking it. Anyway, fixed in v0.8.2. Also published v0.8.3 which is fixes an issue. 

Thanks for reporting, icones is one of the my every day tools 🤗

**Comment by antfu** [comment]
Sorry that I didn't get time to reply with the example code. Thanks for the fix!

**Comment by antfu** [comment]
BTW, I am working on this tonight 😉

![image](https://user-images.githubusercontent.com/11247099/89941720-0359d480-dc4e-11ea-8d95-a0786764cd6d.png)

**Comment by sibbngheid** [comment]
🤩🤩

You are breaking rules 🚀🚀
